### ISSUE TITLE
 Unable to find bower.json 

### ISSUE THREAD

**Issue by bastien-7** [atomfrede/generator-jhipster-leaflet#5]
We are using JHipster 4.14.0.
After generated a JHipster application, we tried to generate a leaflet map thanks to your generator.
Unfortunately, we had the following error :
```
(1/1) Do you want to add ui-leaflet maps? Yes

Unable to find bower.json. Reference to bower dependency (name: ui-leaflet, version:2.0.0) not added.

events.js:137
      throw er; // Unhandled 'error' event
      ^

TypeError: this.debug is not a function
    at Object.addBowerDependency (/home/terrier/Bureau/rando/node_modules/generator-jhipster/generators/generator-base.js:608:18)
    at child.writing (/usr/lib/node_modules/generator-jhipster-leaflet/generators/app/index.js:76:18)
    at /usr/lib/node_modules/generator-jhipster-leaflet/node_modules/yeoman-generator/lib/base.js:430:16
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```
Could you please help us to overcome this problem ?

**Comment by pascalgrimaud** [comment]
This module supports only AngularJS, not Angular or React.
So it's normal it doesn't work
